### PR TITLE
NIFI-13495: PutChroma 'unexpected keyword argument' error

### PR DESCRIPTION
**Pull request by krisztina-zsihovszki**
# Summary

[NIFI-13495](https://issues.apache.org/jira/browse/NIFI-13495)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

### CODE REVIEW

**Review by exceptionfactory — APPROVED** [review]
Thanks for finding and correcting this issue @krisztina-zsihovszki, the specific comment for ignoring the [unused argument](https://docs.astral.sh/ruff/rules/unused-method-argument/) is a good approach. +1 merging

**Comment by exceptionfactory** [comment]
@krisztina-zsihovszki The initial commit to this branch does not have an associated [signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). As a new repository, signed commits are required. If you can sign the commit and push an update, I can proceed to merge.

**Comment by krisztina-zsihovszki** [comment]
@exceptionfactory Please check if the forced pushed commit is signed properly.

**Comment by exceptionfactory** [comment]
Thanks for updating the branch with the signed commit @krisztina-zsihovszki, looks good!

**Pull request merged**
